# -*- coding: utf-8 -*-
"""RGB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORrFo20RSXDN56247y_TSouni9h2xELY
"""

pip install earthpy

!pip install matplotlib-venn

from glob import glob

import earthpy as et
import earthpy.spatial as es
import earthpy.plot as ep

import rasterio as rio

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap

import plotly.graph_objects as go

np.seterr(divide='ignore', invalid='ignore')

S_sentinel_bands = glob("/content/*B?*.tiff")

S_sentinel_bands.sort()

l = []

for i in S_sentinel_bands:
  with rio.open(i, 'r') as f:
    l.append(f.read(1))
    
arr_st = np.stack(l)

ep.plot_bands(arr_st, 
              cmap = 'gist_earth', 
              figsize = (20, 12), 
              cols = 6, 
              cbar = False)
plt.show()

rgb = ep.plot_rgb(arr_st, 
                  rgb=(2,1,0), 
                  figsize=(10, 16))
plt.show()

# RGB Composite Image with Strech for better image

ep.plot_rgb(arr_st,
            rgb=(2, 1, 0),
            stretch=True,
            str_clip=0.2,
            figsize=(10, 16))
plt.show()

ndvi = es.normalized_diff(arr_st[3], arr_st[2])

ep.plot_bands(ndvi, cmap="RdYlGn", cols=1, vmin=-1, vmax=1, figsize=(10, 14))

plt.show()

# clay index
cmr = np.divide(arr_st[3], arr_st[2])

ep.plot_bands(cmr, cmap="RdYlGn", cols=1, vmin=-1, vmax=1, figsize=(10, 14))

plt.show()